name: beverage_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.10.0
  flutter_signin_button: ^1.1.0
  favorite_button: ^0.0.3
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
     - images/

  fonts:
        - family: Pacifico
          fonts:
            - asset: fonts/Pacifico/Pacifico-Regular.ttf
  #          - asset: fonts/Raleway/static/Raleway-ExtraLight.ttf
  #         style: italic
        - family: Josefin
          fonts:
            - asset: fonts/Josefin/JosefinSans-Italic-VariableFont_wght.ttf
            - asset: fonts/Josefin/JosefinSans-VariableFont_wght.ttf
  #         weight: 700

